### ISSUE TITLE
skip lines with noncomforming widths

### ISSUE THREAD

**Issue by adamlenart** [nkrishnaswami/fixed-field-reader#1]
If there are some formatting problems with the file, for example, if there are empty lines or shorter lines in the file, currently  `FixedFieldReaderBase._split` raises a `RowLengthError`. Instead of raising an error, a user might want to simply skip those lines. 

PS thank you for all the work!

**Comment by nkrishnaswami** [comment]
Great idea -- will add something like pandas' `errorbadlines` and `warnbadlines` flags to `read_csv`. Glad you're finding this useful!

**Comment by nkrishnaswami** [comment]
Fixed in 5b3f715
